### ISSUE TITLE
don't get a device in my homey.

### ISSUE THREAD

**Issue by blokj** [erwindon/com.dondorp.homey.byronsx#1]
I installed the app but I cannot add the device in my devices. There is no choice Byron.

**Comment by erwindon** [comment]
Currently the Byron SX driver is only visible in the FLOW screen as an APP. There is a trigger-action and a then-action available. I'll extend the software with device-support soon.

**Comment by erwindon** [comment]
Just uploaded a more extended version.
This one has a driver installation wizard and should make installation even easier.
it takes a few days before this version (1.1.0) is visible in the store.

**Comment by erwindon** [comment]
I caused a few more days delay by not noticing the difference between Submit and Publish, but now its there...
