### ISSUE TITLE
SX30S button press shows alert on Homey Mobile App

### ISSUE THREAD

**Issue by stofferr** [erwindon/com.dondorp.homey.byronsx#2]
Hi Erwin,
When I press my new SX30S button then the mobile app on android shows an alert message; Homey Button Pressed: ##
This is nice for debug purposes but annoying for a practical application of the byron button.
Can this behaviour be removed or be made optional somehow?
Thanks,
Roger

**Comment by erwindon** [comment]
Can you please provide a screenshot of this?

**Comment by stofferr** [comment]
Hi Erwin,
I realized yesterday I must have linked my phone to the button, so I
investigated all the scenes in my device.
Today I found a scene that I created for test purposes but had forgotten to
remove from my Homey.
That means that it was me and not the plugin causing this.
Sorry for the noise. issue can be closed.
Keep up the good work!
Roger

**Comment by erwindon** [comment]
If only everyone was so honest to admit such facts!
Hint: I'll remove the app from beta status after at least 3 positive public reviews...

**Comment by stofferr** [comment]
First review posted for SX series.
Hint: I also own a BY series which may earn you another vote :P

**Comment by stofferr** [comment]
BTW, you can close this (non)-issue
