### ISSUE TITLE
Can you support Byron SX30S please ?

### ISSUE THREAD

**Issue by Hansman351** [erwindon/com.dondorp.homey.byronsx#4]
Thank you.

**Comment by erwindon** [comment]
@Hansman351 can you please point me to a website displaying the Byron SX30S? The only reference I found was for a pushbutton only. Which bell is it used with?

**Comment by Hansman351** [comment]
It is just a pushbutton, I use it with the doorbell Byron SX55.
Thank you

**Comment by erwindon** [comment]
@Hansman351 The SX55 is supported. Therefore any pushbutton that works with it is also supported. Just select a regular SX30 for the pushbutton. But actually there is no difference at all between all of the pushbuttons.
What is the actual problem that you encounter?

**Comment by Hansman351** [comment]
Got it working.
I tried to add it as a device and wouldn't recognise the push button, but in a flow it works. (as described)
Thank you for your help.

**Comment by erwindon** [comment]
ok!
